### ISSUE TITLE
WeChat refund curl error

### ISSUE THREAD

**Issue by grantholle** [yansongda/pay#104]
## 包版本号
2.1

## 问题描述
Refund request gives me a curl error:
cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)

## 报错详情
I am able to use `$wechat->find()` to get my order, but when I try to refund I get the empty response.

```php
$order = [
    'out_trade_no' => 'MKZXAe4KfxP2NcnUbfXLrSFxjHMuuzth',
    'out_refund_no' => 'keD2YPRjcHYju8Z18TehZEK3ai5sPnsT',
    'total_fee' => 1,
    'refund_fee' => 1,
];

return $this->wechat->refund($order);
```

It happens both locally and from the production server.

**Comment by grantholle** [comment]
Here's the relevant stacktrace

```
{"exception":"[object] (GuzzleHttp\\Exception\\ConnectException(code: 0): cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html) at ...vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:185)
[stacktrace]
#0 ...vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(149): GuzzleHttp\\Handler\\CurlFactory::createRejection(Object(GuzzleHttp\\Handler\\EasyHandle), Array)
#1 ...vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(102): GuzzleHttp\\Handler\\CurlFactory::finishError(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#2 ...vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\\Handler\\CurlFactory::finish(Object(GuzzleHttp\\Handler\\CurlHandler), Object(GuzzleHttp\\Handler\\EasyHandle), Object(GuzzleHttp\\Handler\\CurlFactory))
#3 ...vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(28): GuzzleHttp\\Handler\\CurlHandler->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#4 ...vendor/guzzlehttp/guzzle/src/Handler/Proxy.php(51): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#5 ...vendor/guzzlehttp/guzzle/src/PrepareBodyMiddleware.php(66): GuzzleHttp\\Handler\\Proxy::GuzzleHttp\\Handler\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#6 ...vendor/guzzlehttp/guzzle/src/Middleware.php(30): GuzzleHttp\\PrepareBodyMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#7 ...vendor/guzzlehttp/guzzle/src/RedirectMiddleware.php(70): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#8 ...vendor/guzzlehttp/guzzle/src/Middleware.php(60): GuzzleHttp\\RedirectMiddleware->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#9 ...vendor/guzzlehttp/guzzle/src/HandlerStack.php(67): GuzzleHttp\\Middleware::GuzzleHttp\\{closure}(Object(GuzzleHttp\\Psr7\\Request), Array)
#10 ...vendor/guzzlehttp/guzzle/src/Client.php(277): GuzzleHttp\\HandlerStack->__invoke(Object(GuzzleHttp\\Psr7\\Request), Array)
#11 ...vendor/guzzlehttp/guzzle/src/Client.php(125): GuzzleHttp\\Client->transfer(Object(GuzzleHttp\\Psr7\\Request), Array)
#12 ...vendor/guzzlehttp/guzzle/src/Client.php(131): GuzzleHttp\\Client->requestAsync('post', Object(GuzzleHttp\\Psr7\\Uri), Array)
#13 ...vendor/guzzlehttp/guzzle/src/Client.php(89): GuzzleHttp\\Client->request('post', 'secapi/pay/refu...', Array)
#14 ...vendor/yansongda/supports/src/Traits/HasHttpRequest.php(64): GuzzleHttp\\Client->__call('post', Array)
#15 ...vendor/yansongda/supports/src/Traits/HasHttpRequest.php(48): Yansongda\\Pay\\Gateways\\Wechat\\Support->request('post', 'secapi/pay/refu...', Array)
#16 ...vendor/yansongda/pay/src/Gateways/Wechat/Support.php(67): Yansongda\\Pay\\Gateways\\Wechat\\Support->post('secapi/pay/refu...', '<xml><appid><![...', Array)
#17 ...vendor/yansongda/pay/src/Gateways/Wechat.php(174): Yansongda\\Pay\\Gateways\\Wechat\\Support::requestApi('secapi/pay/refu...', Array, 'NCgZ8NCjZoPowPZ...', NULL, NULL)
#18 ...app/Http/Controllers/WeChatController.php(106): Yansongda\\Pay\\Gateways\\Wechat->refund(Array)
```
