### ISSUE TITLE
调用支付宝网站支付出现syntax error, unexpected '?'

### ISSUE THREAD

**Issue by arieslee** [yansongda/pay#152]
## 包版本号
v2.4.3

## 问题描述
ParseError
syntax error, unexpected '?'

## 代码
` $order = [
            'out_trade_no' => $row['order_sn'],
            'total_amount' => $row['order_price'] / 100,
            'subject' => $row['product_name'],

 ];

$config = Yii::$app->params['payment']['alipay'];

$alipay = Pay::alipay($config)->web($order);
`

## 报错详情
`
ParseError: syntax error, unexpected '?' in D:\works\vendor\symfony\http-foundation\Response.php:491

Stack trace:

#0 D:\works\vendor\composer\ClassLoader.php(322): Composer\Autoload\includeFile('D:\works\vendor\composer/../symfony/http-foundation\Response.php')

#1 [internal function]: Composer\Autoload\ClassLoader->loadClass('Symfony\\Compone...')

#2 D:\works\vendor\yansongda\pay\src\Gateways\Alipay\WebGateway.php(75): spl_autoload_call('Symfony\\Compone...')

#3 D:\works\vendor\yansongda\pay\src\Gateways\Alipay\WebGateway.php(52): Yansongda\Pay\Gateways\Alipay\WebGateway->buildPayHtml('https://openapi...', Array)

#4 D:\works\vendor\yansongda\pay\src\Gateways\Alipay.php(252): Yansongda\Pay\Gateways\Alipay\WebGateway->pay('https://openapi...', Array)

#5 D:\works\vendor\yansongda\pay\src\Gateways\Alipay.php(91): Yansongda\Pay\Gateways\Alipay->makePay('Yansongda\\Pay\\G...')

#6 D:\works\vendor\yansongda\pay\src\Gateways\Alipay.php(270): Yansongda\Pay\Gateways\Alipay->pay('Yansongda\\Pay\\G...', Array)

#7 D:\works\frontend\controllers\product\OrderController.php(47): Yansongda\Pay\Gateways\Alipay->__call('web', Array)

#8 [internal function]: frontend\controllers\product\OrderController->actionPayment()

#9 D:\works\vendor\yiisoft\yii2\base\InlineAction.php(57): call_user_func_array(Array, Array)

#10 D:\works\vendor\yiisoft\yii2\base\Controller.php(157): yii\base\InlineAction->runWithParams(Array)

#11 D:\works\vendor\yiisoft\yii2\base\Module.php(528): yii\base\Controller->runAction('payment', Array)

#12 D:\works\vendor\yiisoft\yii2\web\Application.php(103): yii\base\Module->runAction('product/order/p...', Array)

#13 D:\works\vendor\yiisoft\yii2\base\Application.php(386): yii\web\Application->handleRequest(Object(common\components\Request))

#14 D:\works\frontend\web\index.php(16): yii\base\Application->run()

#15 {main}

`

**Comment by yansongda** [comment]
symfony 版本问题，建议 composer update 试试看。

**Comment by arieslee** [comment]
嗯，是的composer update以后就好了
