### ISSUE TITLE
单笔转账到支付宝账户接口，返回时报验签失败错误

### ISSUE THREAD

**Issue by JimChenWYU** [yansongda/pay#157]
## 包版本号

v2.*

## 问题描述

如题目，单笔转账到支付宝账户接口，返回时报验签失败错误，查询订单的接口应该也有这个问题。

虽然是代码抛出异常报错了，但是转账还是成功了，钱已经转到了目标账户。

## 代码

```php
require __DIR__ . '/vendor/autoload.php';

$config = [
    'app_id'         => 'xxxxxx',
    'ali_public_key' => 'xxxxxxxxxxxxxx',
    // 加密方式： **RSA2**
    'private_key'    => 'xxxxxxxxxxxxxxx',
    'log'            => [ // optional
        'file'     => './logs/alipay.log',
        'level'    => 'debug',
        'type'     => 'single', // optional, 可选 daily.
        'max_file' => 30, // optional, 当 type 为 daily 时有效，默认 30 天
    ],
//    'mode'           => 'dev', // optional,设置此参数，将进入沙箱模式
];

$order = [
    'out_biz_no'      => time(),
    'payee_type'      => 'ALIPAY_LOGONID',
    'payee_account'   => 'xxxxxxxxx',
    'payee_real_name' => 'xxxxxxxxxxx',
    'amount'          => '0.10',
];

$result = \Yansongda\Pay\Pay::alipay($config)->transfer($order);
var_dump($result);
```

## 报错详情

```shell
PHP Fatal error:  Uncaught Yansongda\Pay\Exceptions\InvalidSignException: Alipay Sign Verify FAILED in E:\Desktop\test\vendor\yansongda\pay\src\Gateways\Alipay\Support.php:98
Stack trace:
#0 E:\Desktop\test\vendor\yansongda\pay\src\Gateways\Alipay\TransferGateway.php(56): Yansongda\Pay\Gateways\Alipay\Support::requestApi(Array, 'MIIBIjANBgkqhki...')
#1 E:\Desktop\test\vendor\yansongda\pay\src\Gateways\Alipay.php(305): Yansongda\Pay\Gateways\Alipay\TransferGateway->pay('https://openapi...', Array)
#2 E:\Desktop\test\vendor\yansongda\pay\src\Gateways\Alipay.php(116): Yansongda\Pay\Gateways\Alipay->makePay('Yansongda\\Pay\\G...')
#3 E:\Desktop\test\vendor\yansongda\pay\src\Gateways\Alipay.php(88): Yansongda\Pay\Gateways\Alipay->pay('Yansongda\\Pay\\G...', Array)
#4 E:\Desktop\test\index.php(27): Yansongda\Pay\Gateways\Alipay->__call('transfer', Array)
#5 {main}
  thrown in E:\Desktop\test\vendor\yansongda\pay\src\Gateways\Alipay\Support.php on line 98
```

**Comment by JimChenWYU** [comment]
找到原因了，记录一下：
1. 支付宝分为应用公私钥和支付宝公钥
2. 在商户后台上传应用公钥之后可以把支付宝公钥下载下来配置到代码中
3. 验签时用到的**支付宝公钥**，而不是应用公钥
4. 详细文档[地址](https://docs.open.alipay.com/309/106236/)

**Comment by shijunti19** [comment]
@JimChenWYU 到底是阿里公共密钥还是支付宝公钥最好截图下，实在不知道说什么的、完全没有这玩意
