### ISSUE TITLE
单笔转账到支付宝账户接口返回错误码:40002. 支付宝支付没问题

### ISSUE THREAD

**Issue by WalkingNormal** [yansongda/pay#160]
## 包版本号
1.0

## 问题描述
单笔转账到支付宝账户接口返回错误码:40002. 支付宝支付没问题。

## 代码
涉及到 异步通知、同步通知 的问题，请将 nginx/Apache 的相关日志贴出来
```php
             $config_biz = [
                'out_biz_no' => $order_id,                 // 订单号
                'payee_type' => 'ALIPAY_LOGONID',        // 收款方账户类型(ALIPAY_LOGONID | ALIPAY_USERID)
                'payee_account' => $account,            // 收款方账户
                'amount' => $amount,                        // 转账金额
                'payer_show_name' => urlencode('懂你美学'),             // 付款方姓名
                'payee_real_name' => urlencode($truename),             // 收款方真实姓名
                'remark' => urlencode('用户发起提现'),                      // 转账备注
            ];
            /*
             * 转账
             */
            $pay = new Pay($this->config);
            $result =  $pay->driver('alipay')->gateway('transfer')->pay($config_biz);
          
```
## 报错详情
```json
{"message":"get result error:Invalid Arguments - isv.invalid-signature","code":40002,"status_code":500,"debug":{"line":232,"file":"\/home\/wwwroot\/dnmx\/vendor\/yansongda\/pay\/src\/Gateways\/Alipay\/Alipay.php","class":"Yansongda\\Pay\\Exceptions\\GatewayException","trace":["#0 \/home\/wwwroot\/dnmx\/vendor\/yansongda\/pay\/src\/Gateways\/Alipay\/TransferGateway.php(42): Yansongda\\Pay\\Gateways\\Alipay\\Alipay->getResult(Array, 'alipay.fund.tra...')","#1 \/home\/wwwroot\/dnmx\/app\/Api\/Controllers\/UserController.php(607): Yansongda\\Pay\\Gateways\\Alipay\\TransferGateway->pay(Array)","#2 [internal function]: App\\Api\\Controllers\\UserController->cash(Object(Dingo\\Api\\Http\\Request))","#3 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Controller.php(55): call_user_func_array(Array, Array)","#4 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/ControllerDispatcher.php(44): Illuminate\\Routing\\Controller->callAction('cash', Array)","#5 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(204): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Api\\Controllers\\UserController), 'cash')","#6 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Route.php(160): Illuminate\\Routing\\Route->runController()","#7 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(572): Illuminate\\Routing\\Route->run()","#8 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#9 \/home\/wwwroot\/dnmx\/vendor\/tymon\/jwt-auth\/src\/Middleware\/GetUserFromToken.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#10 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Tymon\\JWTAuth\\Middleware\\GetUserFromToken->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#11 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#12 \/home\/wwwroot\/dnmx\/app\/Http\/Middleware\/UserChange.php(24): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#13 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): App\\Http\\Middleware\\UserChange->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#14 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#15 \/home\/wwwroot\/dnmx\/vendor\/dingo\/api\/src\/Http\/Middleware\/PrepareController.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#16 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#17 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#18 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))","#19 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(574): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#20 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(533): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))","#21 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Router.php(511): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))","#22 \/home\/wwwroot\/dnmx\/vendor\/dingo\/api\/src\/Routing\/Adapter\/Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#23 \/home\/wwwroot\/dnmx\/vendor\/dingo\/api\/src\/Routing\/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')","#24 \/home\/wwwroot\/dnmx\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))","#25 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))","#26 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#27 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#28 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#29 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#30 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#31 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#32 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Middleware\/CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#33 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))","#34 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))","#35 \/home\/wwwroot\/dnmx\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#36 \/home\/wwwroot\/dnmx\/vendor\/dingo\/api\/src\/Http\/Middleware\/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))","#37 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(148): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Illuminate\\Http\\Request), Object(Closure))","#38 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Routing\/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))","#39 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Pipeline\/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))","#40 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))","#41 \/home\/wwwroot\/dnmx\/vendor\/laravel\/framework\/src\/Illuminate\/Foundation\/Http\/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))","#42 \/home\/wwwroot\/dnmx\/public\/index.php(54): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))","#43 {main}"]}}
```

**Comment by yansongda** [comment]
payer_show_name  等需要 urlencode 吗？

**Comment by WalkingNormal** [comment]
[支付宝公共错误码](https://docs.open.alipay.com/common/105806) .正因为出现这个问题，根据这个提示才增加了 `urlencode` 编码调试。现在加不加 `urlencode` ,仍然还是 40002的错误提示

**Comment by WalkingNormal** [comment]
```php
    protected $config = [
        'alipay' => [
            'app_id' => '2018082761125646',
            'notify_url' => 'http://www.wdongni.com/api/classroom/alipay_notify',
            'return_url' => 'http://www.wdongni.com/api/classroom/alipay_notify',
            'ali_public_key' => 'MIIBIjANBgkqhkiG9w0', // 只展示部分信息 
            'private_key'=>'MIIEpQIBAAKCAQEA51u' //  只展示部分信息
        ],
        'wechat' => [
        ]
    ];

            $config_biz = [
                'out_biz_no' => $order_id,                 // 订单号
                'payee_type' => 'ALIPAY_LOGONID',        // 收款方账户类型(ALIPAY_LOGONID | ALIPAY_USERID)
                'payee_account' => $account,            // 收款方账户
                'amount' => $amount,                        // 转账金额
                'payer_show_name' => '懂你美学',             // 付款方姓名
                'payee_real_name' => $truename,             // 收款方真实姓名
                'remark' => '用户发起提现',                      // 转账备注
            ];

```

> 项目就剩下这一个点了，环境都是PHP5.6

**Comment by yansongda** [comment]
我刚沙箱环境测试无问题，您自己可排查看看。注意参数长度， amount 等是否越界等。

**Comment by yijiepifu** [comment]
扫码支付也报错：`{"msg":{"alipay_trade_precreate_response":{"code":"40002","msg":"Invalid Arguments","sub_code":"isv.invalid-signature","sub_msg":"验签出错，建议检查签名字符串或签名私钥与应用公钥是否匹配，网关生成的验签字符串为：`
用支付宝官方demo没问题

**Comment by yansongda** [comment]
@yijiepifu 签名问题，和本 issue 不是一类问题。自行查看 文档进行解决

感谢支持

**Comment by lzygjq** [comment]
demo拿过来基本不能用，直接报错ERROR_GATEWAY: Get Alipay API Error:Invalid Arguments - isv.invalid-signature

**Comment by lzygjq** [comment]
> demo composer下来基本不能用，直接报错ERROR_GATEWAY: Get Alipay API Error:Invalid Arguments - isv.invalid-signature。用的是laravel框架

ali 官方demo可以跑通

**Comment by shijunti19** [comment]
也报错了奇怪Yansongda \ Pay \ Exceptions \ GatewayException (4)
ERROR_GATEWAY: Get Alipay API Error:Invalid Arguments - isv.invalid-signature
