### ISSUE TITLE
退款异步通知出现 Convert To Array Error! Invalid Xml!

### ISSUE THREAD

**Issue by cdhraesaemer** [yansongda/pay#172]
## 包版本号
2.5.1

## 问题描述
2018.10.11开始出现
退款异步通知 出现 Convert To Array Error! Invalid Xml!

## 代码
nginx日志：
58.251.80.53--[ll/Oct/2018:16:00:05+0800]"POST/api/notify/wxpay/refund HTTP/l.1" 200 96 "-" "Mozilla/4.0"

## 报错详情
退款异步通知 出现 Convert To Array Error! Invalid Xml!

**Comment by yansongda** [comment]
麻烦将日志贴出来。

感谢支持

**Comment by pretendtrue** [comment]
这个是laravel日志
```
[2018-10-12 09:19:16] local.ERROR: Convert To Array Error! Invalid Xml! {"exception":"[object] (Yansongda\\Pay\\Exceptions\\InvalidArgumentException(code: 3): Convert To Array Error! Invalid Xml! at /data/wwwroot/lilianwang/vendor/yansongda/pay/src/Gateways/Wechat/Support.php:319)
[stacktrace]
#0 /data/wwwroot/lilianwang/vendor/yansongda/pay/src/Gateways/Wechat.php(168): Yansongda\\Pay\\Gateways\\Wechat\\Support::fromXml('')
#1 /data/wwwroot/lilianwang/lilianwang/Modules/Order/Model/Order.php(381): Yansongda\\Pay\\Gateways\\Wechat->verify('', true)
#2 /data/wwwroot/lilianwang/lilianwang/Modules/Pay/Service/PaymentService.php(215): Lilianwang\\Order\\Model\\Order->wechatRefundNotify()
#3 /data/wwwroot/lilianwang/lilianwang/Modules/Pay/Controller/PaymentController.php(87): Lilianwang\\Pay\\Service\\PaymentService->wechatRefundNotify()
#4 [internal function]: Lilianwang\\Pay\\Controller\\PaymentController->wechatRefundNotify()
#5 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#6 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('wechatRefundNot...', Array)
#7 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Route.php(212): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(Lilianwang\\Pay\\Controller\\PaymentController), 'wechatRefundNot...')
#8 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Route.php(169): Illuminate\\Routing\\Route->runController()
#9 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Router.php(658): Illuminate\\Routing\\Route->run()
#10 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#11 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#12 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Router.php(660): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#13 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Router.php(635): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#14 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Router.php(601): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#15 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Router.php(590): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#16 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#17 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#18 /data/wwwroot/lilianwang/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#19 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#20 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#21 /data/wwwroot/lilianwang/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#22 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#23 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#24 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#25 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#28 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#29 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#30 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#31 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#32 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#33 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#34 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#35 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#36 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#38 /data/wwwroot/lilianwang/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#39 /data/wwwroot/lilianwang/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#40 {main}
"} 
```
以下是我的回调验证代码
```
// 给微信的失败响应
        $failXml = '<xml><return_code><![CDATA[FAIL]]></return_code><return_msg><![CDATA[FAIL]]></return_msg></xml>';
        $data = app('wechat_pay')->verify(null, true);
        
        // 没有找到对应的订单，原则上不可能发生，保证代码健壮性
        if(!$order = $this->where('order_sn', $data['out_trade_no'])->first()) {
            return $failXml;
        }

        if ($data['return_code'] === 'SUCCESS') {
            // 退款成功，将订单退款状态改成退款成功
            $order->update([
                'order_status' => $order->order_status == 2 ? 3 : 6,
            ]);

            // 商品库存增加
            foreach ($order->orderGoods as $goods) {
                $goods->goodsSku->addStock($goods->number);
            }

            // 退货退款订单表状态修改
            $reject = $order->rejectOrder()->whereApplyReturnGoodsTime($order->apply_return_goods_time)->first();
            if ($reject) {
                $reject->reject_status = 2;
                $reject->save();
            }

        } else {
            // 退款失败，将具体状态存入 extra 字段，并表退款状态改成失败
            $order->update([
                'order_status' => config('order.order_status.refund_fail')
            ]);
        }

        return app('wechat_pay')->success();
```

**Comment by yansongda** [comment]
SDK 自带的日志有吗？

**Comment by pretendtrue** [comment]
```
2018-10-12 09:43:01 > DEBUG > Wechat Generate Sign Content Before Trim [{"appid":"省略","mch_id":"省略","nonce_str":"Ocz5RD8rkzjHdW7Z","notify_url":"https://test.pretendtrue.com/payment/wechat/refund_notify","out_refund_no":"20181012094301462241995","out_trade_no":"20181012090412158641842","refund_fee":1,"sign":"","spbill_create_ip":null,"total_fee":1},"appid=省略&mch_id=省略&nonce_str=Ocz5RD8rkzjHdW7Z&notify_url=https://test.pretendtrue.com/payment/wechat/refund_notify&out_refund_no=20181012094301462241995&out_trade_no=20181012090412158641842&refund_fee=1&total_fee=1&"] 

2018-10-12 09:43:01 > DEBUG > Wechat Generate Sign Before UPPER [{"appid":"省略","mch_id":"省略","nonce_str":"Ocz5RD8rkzjHdW7Z","notify_url":"https://test.pretendtrue.com/payment/wechat/refund_notify","out_refund_no":"20181012094301462241995","out_trade_no":"20181012090412158641842","refund_fee":1,"sign":"","spbill_create_ip":null,"total_fee":1},"1e52e381df7ea7df892de789b0c9cf9c"] 

2018-10-12 09:43:01 > INFO > Starting To Refund An Wechat Order ["https://api.mch.weixin.qq.com/",{"appid":"省略","mch_id":"省略","nonce_str":"Ocz5RD8rkzjHdW7Z","notify_url":"https://test.pretendtrue.com/payment/wechat/refund_notify","sign":"1E52E381DF7EA7DF892DE789B0C9CF9C","spbill_create_ip":null,"out_trade_no":"20181012090412158641842","total_fee":1,"refund_fee":1,"out_refund_no":"20181012094301462241995"}] 

2018-10-12 09:43:01 > DEBUG > Request To Wechat Api ["https://api.mch.weixin.qq.com/secapi/pay/refund",{"appid":"省略","mch_id":"省略","nonce_str":"Ocz5RD8rkzjHdW7Z","notify_url":"https://test.pretendtrue.com/payment/wechat/refund_notify","sign":"1E52E381DF7EA7DF892DE789B0C9CF9C","spbill_create_ip":null,"out_trade_no":"20181012090412158641842","total_fee":1,"refund_fee":1,"out_refund_no":"20181012094301462241995"}] 

2018-10-12 09:43:01 > DEBUG > Result Of Wechat Api {"return_code":"SUCCESS","return_msg":"OK","appid":"省略","mch_id":"省略","nonce_str":"4JlFIThCvIuTHDkw","sign":"86992C0FE47AC627132CD30172A294F8","result_code":"FAIL","err_code":"ERROR","err_code_des":"订单已全额退款"}
```

**Comment by yansongda** [comment]
> #1 /data/wwwroot/lilianwang/lilianwang/Modules/Order/Model/Order.php(381): Yansongda\\Pay\\Gateways\\Wechat->verify('', true)

执行到这里，verify 第一个参数成了 空， 请问可以查明什么原因吗？

PS：您刚刚发的日志，没有 异步通知相关的日志哦

**Comment by pretendtrue** [comment]
空的原因是这块
`$data = app('wechat_pay')->verify(null, true);`
异步通知的那块应该如何获取到，不太懂

**Comment by cdhraesaemer** [comment]
SDK Log:
2018-10-11 15:40:36 > INFO > Received Wechat Request ["<xml><return_code>SUCCESS</return_code><appid><![CDATA[00000000000]]></appid><mch_id><![CDATA[1504000000]]></mch_id><nonce_str><![CDATA[0000000000000000000000000000]]></nonce_str><req_info><![CDATA[YbWafewDSugCBifmpu9KldS6r6TR3XRT6hBWb2RYy0ysJUxofD6cIwwSQwWEnxRZ1z5bBduH0iSQ9xC0Ve20j3qJXUPZaZklh1VKv8xSRrlORJZv0OFQWgTqu1j/OnrdrqQRRHSWUleZ1UIcWLcUlQEVfXbh2WDeAzSt9Jhe55GLOkbwda3Du1xiYZkHY4T7f8efk4gYMI5NB3f7LaJyAjDM6TeZJZHj/Ksllk/rrlAa+r+r32OwUasrXDmqRw+WOxSjBJSjUrTmKXiQKxOcxQhOrdM/0hGG+YHXZpay3mTk9bGbbAXR5IEBbhAsVvBSAfESxrDRyQS+8/K3VEj3137uHaUiYBCf56iq1jRttDgNDOxP6TFv/UuAugRlQhzveDLvdLXuzVp+8Sh/thOI97ReEkQxxx6bDqjaHt7VkYaNhmubqVeuLP+tRg/ncR3sXyHgF0RcVYDiHml4Bm4w945f7HJuRkZJvuSHC0MNLvIeMxsh5qsGrCNrilbfOdhYAuNu2t+0nazsCAaXKBH0NLSW8BjIoMKbnXzWML+aekihVugyptV2uqQcUaTcQ15VJW9+FneLJFc/aunwAAVsGoBLYLvFi3fksrWMynynbPvGHDDvnPvxFzVrH4ReidlHSDi966YahhnLZuHfhE8Bo6jzrEV3X2vnVIFoXxfGVvMYtqfWM9nvawDDajO5ro+1Nvlu1GXp/R5PoExoRBgSpQHxEsaw0ckEvvPyt1RI99dGJ2MafPf0yWjAHYrawgK2tu/ejTTNN4zID3KXl91kEeTCRNOwyHiBD81jIVRKZT73o+h+fHdKeuYR7YHHTRQBQXBEmrLIZtFtFY4L3JvXpGyEopajs5ki0C4Kb5746EzHplIwHEMxqUFuVMkm1qEryMkNOOJC3SNUqYlTX1NN22PQG6aLbBrMye59oXKjacyRw7BFOkjwBOVJ4plwyg7D96Pofnx3SnrmEe2Bx00UAdIDBoxUemWS0Vz9VcT/bs0wDdAkTkJDG9y4gRjRCAlKuGfZomhApeotfj38pSu8DDn+WCGU4eBxY874SjWIlYjPW9FHr9Hfas7h5WSv+l1KXLb+LYegVYlldHB72z6qkusxgDVELZmM4EYnZW02VbU=]]></req_info></xml>"] 


![_20181012105311](https://user-images.githubusercontent.com/3795018/46845232-1d85ba00-ce0d-11e8-8262-79faccd21412.png)
红框里返回false

**Comment by cdhraesaemer** [comment]
2018-10-11 15:40:36 > INFO > Received Wechat Request ["<xml><return_code>SUCCESS</return_code><appid><![CDATA[]]></appid><mch_id><![CDATA[]]></mch_id><nonce_str><![CDATA[]]></nonce_str><req_info><![CDATA[YbWafewDSugCBifmpu9KldS6r6TR3XRT6hBWb2RYy0ysJUxofD6cIwwSQwWEnxRZ1z5bBduH0iSQ9xC0Ve20j3qJXUPZaZklh1VKv8xSRrlORJZv0OFQWgTqu1j/OnrdrqQRRHSWUleZ1UIcWLcUlQEVfXbh2WDeAzSt9Jhe55GLOkbwda3Du1xiYZkHY4T7f8efk4gYMI5NB3f7LaJyAjDM6TeZJZHj/Ksllk/rrlAa+r+r32OwUasrXDmqRw+WOxSjBJSjUrTmKXiQKxOcxQhOrdM/0hGG+YHXZpay3mTk9bGbbAXR5IEBbhAsVvBSAfESxrDRyQS+8/K3VEj3137uHaUiYBCf56iq1jRttDgNDOxP6TFv/UuAugRlQhzveDLvdLXuzVp+8Sh/thOI97ReEkQxxx6bDqjaHt7VkYaNhmubqVeuLP+tRg/ncR3sXyHgF0RcVYDiHml4Bm4w945f7HJuRkZJvuSHC0MNLvIeMxsh5qsGrCNrilbfOdhYAuNu2t+0nazsCAaXKBH0NLSW8BjIoMKbnXzWML+aekihVugyptV2uqQcUaTcQ15VJW9+FneLJFc/aunwAAVsGoBLYLvFi3fksrWMynynbPvGHDDvnPvxFzVrH4ReidlHSDi966YahhnLZuHfhE8Bo6jzrEV3X2vnVIFoXxfGVvMYtqfWM9nvawDDajO5ro+1Nvlu1GXp/R5PoExoRBgSpQHxEsaw0ckEvvPyt1RI99dGJ2MafPf0yWjAHYrawgK2tu/ejTTNN4zID3KXl91kEeTCRNOwyHiBD81jIVRKZT73o+h+fHdKeuYR7YHHTRQBQXBEmrLIZtFtFY4L3JvXpGyEopajs5ki0C4Kb5746EzHplIwHEMxqUFuVMkm1qEryMkNOOJC3SNUqYlTX1NN22PQG6aLbBrMye59oXKjacyRw7BFOkjwBOVJ4plwyg7D96Pofnx3SnrmEe2Bx00UAdIDBoxUemWS0Vz9VcT/bs0wDdAkTkJDG9y4gRjRCAlKuGfZomhApeotfj38pSu8DDn+WCGU4eBxY874SjWIlYjPW9FHr9Hfas7h5WSv+l1KXLb+LYegVYlldHB72z6qkusxgDVELZmM4EYnZW02VbU=]]></req_info></xml>"] 

![_20181012105311](https://user-images.githubusercontent.com/3795018/46845278-59b91a80-ce0d-11e8-830b-c94c58ed87cc.png)
红框里返回false

**Comment by cdhraesaemer** [comment]
回复中日志里面内容在github上不显示？

**Comment by pretendtrue** [comment]
因为是与这个问题无关，所以被我删除了。

**Comment by cdhraesaemer** [comment]
但是日志记录不是空啊，我更新了上条回复的 SDK日志 这回能显示全了

**Comment by cdhraesaemer** [comment]
调试和输出结果
![_20181012113017](https://user-images.githubusercontent.com/3795018/46846457-5aa07b00-ce12-11e8-84f6-03cb5f5e26dc.png)

![_20181012113105](https://user-images.githubusercontent.com/3795018/46846464-5d02d500-ce12-11e8-87d0-6df3577b5361.png)

**Comment by yansongda** [comment]
返回 false  代表解密失败，您自行用脚本测试下是否能解密成功

**Comment by pretendtrue** [comment]
请问是否有解决到问题？

**Comment by Captain1** [comment]
版本：2.8
微信普通支付：异步通知OK，在同步回调（设置了return_url,即redirect_url)，里面无法进行验签，同标题的报错。
是不是腾讯后台只在异步回调里带参数，同步回调（下图第七步）不带？那我同步回调里应该查询后台，或者查单的操作，来确定是否支付成功吧？望解答。
[](https://pay.weixin.qq.com/wiki/doc/api/img/chapter15_1.png)
