### ISSUE TITLE
小程序支付getResult error:签名错误

### ISSUE THREAD

**Issue by DreamboyA** [yansongda/pay#41]
## 问题描述
小程序支付getResult error:签名错误，miniapp_id、mch_id、key核对好几遍了没有问题，但是还是一直保持

## 报错详情
<pre>
<code>
{
    "message": "getResult error:签名错误",
    "code": 20000,
    "status_code": 500,
    "debug": {
        "line": 219,
        "file": "/home/vagrant/Code/Laravel/ShareLoverServer/vendor/yansongda/pay/src/Gateways/Wechat/Wechat.php",
        "class": "Yansongda\\Pay\\Exceptions\\GatewayException",
        "trace": [
            "#0 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/yansongda/pay/src/Gateways/Wechat/Wechat.php(179): Yansongda\\Pay\\Gateways\\Wechat\\Wechat->getResult('pay/unifiedorde...')",
            "#1 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/yansongda/pay/src/Gateways/Wechat/MiniappGateway.php(42): Yansongda\\Pay\\Gateways\\Wechat\\Wechat->preOrder(Array)",
            "#2 /home/vagrant/Code/Laravel/ShareLoverServer/app/Api/Controllers/Order/OrderController.php(210): Yansongda\\Pay\\Gateways\\Wechat\\MiniappGateway->pay(Array)",
            "#3 [internal function]: App\\Api\\Controllers\\Order\\OrderController->create(Object(Dingo\\Api\\Http\\Request))",
            "#4 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)",
            "#5 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('create', Array)",
            "#6 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Api\\Controllers\\Order\\OrderController), 'create')",
            "#7 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Route.php(162): Illuminate\\Routing\\Route->runController()",
            "#8 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(610): Illuminate\\Routing\\Route->run()",
            "#9 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#10 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/tymon/jwt-auth/src/Middleware/GetUserFromToken.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#11 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Tymon\\JWTAuth\\Middleware\\GetUserFromToken->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#12 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#13 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/dingo/api/src/Http/Middleware/PrepareController.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#14 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Dingo\\Api\\Http\\Middleware\\PrepareController->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#15 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#16 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#17 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#18 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(571): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Dingo\\Api\\Http\\Request))",
            "#19 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Router.php(549): Illuminate\\Routing\\Router->dispatchToRoute(Object(Dingo\\Api\\Http\\Request))",
            "#20 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/dingo/api/src/Routing/Adapter/Laravel.php(81): Illuminate\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#21 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/dingo/api/src/Routing/Router.php(513): Dingo\\Api\\Routing\\Adapter\\Laravel->dispatch(Object(Dingo\\Api\\Http\\Request), 'v1')",
            "#22 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/dingo/api/src/Http/Middleware/Request.php(126): Dingo\\Api\\Routing\\Router->dispatch(Object(Dingo\\Api\\Http\\Request))",
            "#23 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(114): Dingo\\Api\\Http\\Middleware\\Request->Dingo\\Api\\Http\\Middleware\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#24 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/fideloper/proxy/src/TrustProxies.php(56): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#25 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Fideloper\\Proxy\\TrustProxies->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#26 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#27 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#28 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(30): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#29 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#30 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#31 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#32 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(46): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#33 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#34 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Dingo\\Api\\Http\\Request))",
            "#35 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/dingo/api/src/Http/Middleware/Request.php(127): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#36 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/dingo/api/src/Http/Middleware/Request.php(103): Dingo\\Api\\Http\\Middleware\\Request->sendRequestThroughRouter(Object(Dingo\\Api\\Http\\Request))",
            "#37 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(149): Dingo\\Api\\Http\\Middleware\\Request->handle(Object(Dingo\\Api\\Http\\Request), Object(Closure))",
            "#38 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))",
            "#39 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(102): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))",
            "#40 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))",
            "#41 /home/vagrant/Code/Laravel/ShareLoverServer/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))",
            "#42 /home/vagrant/Code/Laravel/ShareLoverServer/public/index.php(55): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))",
            "#43 {main}"
        ]
    }
}
</code>
</pre>

**Comment by DreamboyA** [comment]
已解决，因为金额为传入为0，0以上就可以了
