### ISSUE TITLE
\Yansongda\Pay\Plugin\Wechat\Shortcut\MpShortcut 从容器中找不到。

### ISSUE THREAD

**Issue by bupthui** [yansongda/pay#589]
## 包版本号
v3.1.0

## 问题描述
由v3.0.27 => v3.1.0后，调用发起支付接口，报错{"exception":"[object] (Yansongda\\Pay\\Exception\\ServiceNotFoundException(code: 2001):

## 你的代码

Pay::setContainer($this->container);
                        $s = Pay::config(array_merge($this->config, ['_force' => true]));
                        return Pay::wechat()->wap($order);

## 报错详情
[2022-03-16 18:29:18] local.ERROR:  {"exception":"[object] (Yansongda\\Pay\\Exception\\ServiceNotFoundException(code: 2001):  at /Users/c/vendor/yansongda/pay/src/Pay.php:180)
[stacktrace]
#0 /Users/c/vendor/yansongda/pay/src/Provider/AbstractProvider.php(41): Yansongda\\Pay\\Pay::get('\\\\Yansongda\\\\Pay\\\\...')
#1 /Users/c/vendor/yansongda/pay/src/Provider/Wechat.php(54): Yansongda\\Pay\\Provider\\AbstractProvider->call('\\\\Yansongda\\\\Pay\\\\...', Array)

## sdk 日志

无

## nginx/apache 日志
> 涉及到 异步通知、同步通知 的问题，请贴出来

经简单排查发现是 service \Yansongda\Pay\Plugin\Wechat\Shortcut\MpShortcut 从容器中找不到。

**Comment by bupthui** [comment]
所有shortcut相关的都无法从容器中获取，以至于报错

**Comment by yansongda** [comment]
框架哪个？升级有没有按照 https://pay.yansongda.cn/docs/v3/upgrade/v3.1.html#php-%E6%9C%80%E4%BD%8E%E7%89%88%E6%9C%AC  指引来？

**Comment by bupthui** [comment]
框架用的比较老的laravel 5.6，php版本是7.4

**Comment by yansongda** [comment]
`Pay::setContainer($this->container);`

为什么加这个？

**Comment by bupthui** [comment]
加不加这个，效果是一摸一样的，没有任何区别。
[2022-03-16 18:35:01] local.INFO: service Yansongda\Pay\Contract\ConfigInterface 可以从容器中拿到
[2022-03-16 18:35:01] local.INFO: service Yansongda\Pay\Contract\ConfigInterface 可以从容器中拿到
[2022-03-16 18:35:01] local.INFO: service wechat 可以从容器中拿到
[2022-03-16 18:35:01] local.INFO: service \Yansongda\Pay\Plugin\Wechat\Shortcut\MpShortcut  报错 `Yansongda\\Pay\\Exception\\ServiceNotFoundException`

**Comment by yansongda** [comment]
你弄一个最小的复现 demo 吧

**Comment by luolaihui110** [comment]
同样出现了这个问题，laravel 5.5
