### ISSUE TITLE
微信支付通知在swoole下报错

### ISSUE THREAD

**Issue by Obacm** [yansongda/pay#625]
## 包版本号
v3.1

## 问题描述
微信支付通知在swoole下报错

## 你的代码
```
$data = Pay::wechat()->callback(ServerRequestInterface::class);
```

## 报错详情
```
[2022-07-08 11:28:19] production.ERROR: Provider response Error {"exception":"[object] (Yansongda\\Pay\\Exception\\InvalidResponseException(code: 5007): Provider response Error at /home/wwwroot/dev-mini.popkuji.com/vendor/yansongda/pay/src/Functions.php:282)
[stacktrace]
#0 /home/wwwroot/dev-mini.popkuji.com/vendor/yansongda/pay/src/Plugin/Wechat/CallbackPlugin.php(40): decrypt_wechat_resource()
#1 /home/wwwroot/dev-mini.popkuji.com/vendor/yansongda/supports/src/Pipeline.php(126): Yansongda\\Pay\\Plugin\\Wechat\\CallbackPlugin->assembly()
#2 /home/wwwroot/dev-mini.popkuji.com/vendor/yansongda/supports/src/Pipeline.php(84): Yansongda\\Supports\\Pipeline->Yansongda\\Supports\\{closure}()
#3 /home/wwwroot/dev-mini.popkuji.com/vendor/yansongda/pay/src/Provider/AbstractProvider.php(70): Yansongda\\Supports\\Pipeline->then()
#4 /home/wwwroot/dev-mini.popkuji.com/vendor/yansongda/pay/src/Provider/Wechat.php(128): Yansongda\\Pay\\Provider\\AbstractProvider->pay()
#5 /home/wwwroot/dev-mini.popkuji.com/app/Http/Controllers/V1/NotifyController.php(16): Yansongda\\Pay\\Provider\\Wechat->callback()
#6 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): App\\Http\\Controllers\\V1\\NotifyController->wechat()
#7 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction()
#8 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(261): Illuminate\\Routing\\ControllerDispatcher->dispatch()
#9 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(204): Illuminate\\Routing\\Route->runController()
#10 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(725): Illuminate\\Routing\\Route->run()
#11 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}()
#12 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#13 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle()
#14 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(33): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#15 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->Laravel\\Sanctum\\Http\\Middleware\\{closure}()
#16 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#17 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/sanctum/src/Http/Middleware/EnsureFrontendRequestsAreStateful.php(34): Illuminate\\Pipeline\\Pipeline->then()
#18 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Laravel\\Sanctum\\Http\\Middleware\\EnsureFrontendRequestsAreStateful->handle()
#19 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#20 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then()
#21 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack()
#22 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute()
#23 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute()
#24 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch()
#25 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}()
#26 /home/wwwroot/dev-mini.popkuji.com/app/Http/Middleware/JsonMiddleware.php(14): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#27 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): App\\Http\\Middleware\\JsonMiddleware->handle()
#28 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#29 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#30 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle()
#31 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#32 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle()
#33 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle()
#34 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#35 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle()
#36 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#37 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle()
#38 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(62): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#39 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\HandleCors->handle()
#40 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#41 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle()
#42 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}()
#43 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then()
#44 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter()
#45 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/octane/src/ApplicationGateway.php(36): Illuminate\\Foundation\\Http\\Kernel->handle()
#46 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/octane/src/Worker.php(92): Laravel\\Octane\\ApplicationGateway->handle()
#47 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/octane/bin/swoole-server(118): Laravel\\Octane\\Worker->handle()
#48 [internal function]: {closure}()
#49 /home/wwwroot/dev-mini.popkuji.com/vendor/laravel/octane/bin/swoole-server(164): Swoole\\Server->start()
#50 {main}
"} 
```

## sdk 日志
无

## nginx/apache 日志
>  nginx  101.226.103.24 - - [08/Jul/2022:11:12:08 +0800] "POST /api/v1/notify/wechat HTTP/1.1" 400 48 "-" "Mozilla/4.0

**Comment by puzzle9** [comment]
解决了吗 如何解决的呀

**Comment by puzzle9** [comment]
> 解决了吗 如何解决的呀

研究了半天 发现是自己的密钥配置错了

解决方案

- https://laravel.com/docs/10.x/requests#psr7-requests

```php
<?php

namespace App\Http\Controllers;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use Psr\Http\Message\ServerRequestInterface;

use Yansongda\LaravelPay\Facades\Pay;

class Notifly extends Controller
{
    public function wechat(ServerRequestInterface $request)
    {
        $wechat = Pay::wechat();

        $result = $wechat->callback($request);

        // ...

        return $wechat->success();
    }

    public function alipay(Request $request)
    {
        $alipay = Pay::alipay();

        $result = $alipay->callback($request->all());

        // ...

        return $alipay->success();
    }
}

```
